# Site
name: Above Ground Level
description: Aviation News
meta_description: "Aviation blog"
logo: 'assets/images/mainlogo.png'
favicon: 'assets/images/logofooter.png'
paginate: 8
baseurl:
email: 'aqn.andrew@gmail.com'
google_analytics: ''
disqus: ''
sharethis:

# Authors
authors:
  Andy:
    name: Andy
    display_name:
    gravatar:
    email:
    web:
    twitter:
    description: "My name is Andy and I am a Aircraft Dispatcher. Holla!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
